---
# tasks file for ansible-role-prometheus-node-exporter

- name: download Prometheus Node Exporter
  include_tasks: download.yml

- name: install Prometheus Exporter
  include_tasks: install-prometheus-exporter.yml

- name: configure Prometheus Exporter
  include_tasks: configure-prometheus-exporter.yml

- name: manage firewalld
  include_tasks: manage_firewalld.yml
  when: prometheus_node_exporter_manage_firewalld
