---
#
# Configure Prometheus Node Exporter firewalld
#

- name: install firewalld package
  package:
    name: firewalld
    state: present

- name: ensure firewalld is running and enabled on boot
  service:
    name: firewalld
    state: started
    enabled: true

- name: 'configure firewalld for port {{ prometheus_node_exporter_port }}'
  firewalld:
    port: '{{ prometheus_node_exporter_port }}/tcp'
    permanent: true
    immediate: true
    state: enabled
    source: '{{ item }}'
  with_items:
    - '{{ prometheus_node_exporter_source }}'
  when: not prometheus_node_exporter_manage_firewalld_use_zone

- name: 'configure firewalld for http port {{ prometheus_node_exporter_port }}'
  firewalld:
    port: '{{ prometheus_node_exporter_port }}/tcp'
    permanent: true
    immediate: true
    state: enabled
    zone: '{{ prometheus_node_exporter_zone }}'
  when: prometheus_node_exporter_manage_firewalld_use_zone
